# Generated by Django 5.2 on 2025-04-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_type_event_organiser_comment_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
