# Generated by Django 5.2 on 2025-04-06 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_event_options_event_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='interested',
            field=models.ManyToManyField(blank=True, related_name='interested', to=settings.AUTH_USER_MODEL),
        ),
    ]
